import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ReduxProvider from "@/redux/redux-provider";
import ReactQueryProvider from "@/lib/reactQueryClient";
import CustomToastContainer from "@/lib/customToastContainer";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie Insight Forum",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const messages = await getMessages();
  return (
    <html lang={params.locale} suppressHydrationWarning>
      <body className={inter.className}>
        <ReduxProvider>
          <ReactQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NextIntlClientProvider messages={messages}>
                {children}
              </NextIntlClientProvider>
              <CustomToastContainer />
            </ThemeProvider>
            <ReactQueryDevtools initialIsOpen={false} />
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
